### ISSUE TITLE
Uploaded file response is not correct 

### ISSUE THREAD

**Issue by BenderScript** [magengit/magen-io#8]
The function build_file_upload_response() builds the response for uploaded files. It works when ingestion is used stand-alone, but not when file is uploaded through magen-io.

The reason is that the returned URL used ingestion port (5020) and not magen-io port (5005). The problematic line is:

    file_dict["url"] = server_urls_instance.ingestion_server_single_asset_url.format(asset["uuid"])

This function needs to return the proper URL depending whether it is used in ingestion stand-laone or from magen-io

**Comment by lokodali** [comment]
"Uploaded file response is not correct Closes #8" commit from pull request 4 in magen-in closes #8
